### ISSUE TITLE
Observed difference in output between MultiplexerConverter and WkHtmlToPdfConverter

### ISSUE THREAD

**Issue by JulianMay** [pruiz/WkHtmlToXSharp#46]
Both screenshots is output from the same html report.
The only difference in the calling code is which class is new'ed up as the responsible IHtmlToPdfConverter
Seems to me like a bug in WkHtmlToPdfConverter?
I'm using MultiplexerConverter so no trouble for my, just wanted to report it since I saw it.
![withwkhtmltopodfconverter](https://user-images.githubusercontent.com/1412348/31662665-a1399fd6-b33f-11e7-9f5a-c4c8a8016dd0.png)
![withmultiplexingconverter](https://user-images.githubusercontent.com/1412348/31662667-a1730c6c-b33f-11e7-823e-5b8c5f58b71f.png)

Thanks for making this!

**Comment by pruiz** [comment]
Can you paste some code for each case? I guess you are probably using (and disposing before second use) an WkHtmlToPdfConverter instance. Something which should not be done.

WkHtmlToPdfConverter is the raw adaptation of wkhtmltox engine, if you instantiate it twice (or instantiate, dispose, instantiate a new instance), within a single process, stuff goes out of the window.. :)

That's why MultipexingConverter exists. It takes care of just initializing wkhtmltox once.. and (partially) dispose it when not in use..

**Comment by JulianMay** [comment]
Ok, I'll just keep off WkHtmlToPdfConverter altogether and only use MultipexingConverter.
Yes, it was wrapped in a using scope (because i noticed the implementation of IDisposable).
I'll show myself out.
